### ISSUE TITLE
Strange line-breaks on communities with icons

### ISSUE THREAD

**Issue by poVoq** [LemmyNet/lemmy-ui#121] opened 2021-01-07 21:25 UTC
Happens on Firefox (latest, Linux version):
![community](https://user-images.githubusercontent.com/940360/103946699-7ba5c280-5126-11eb-8e1c-57c9182fa5c8.png)

**Comment by dessalines** [comment] 2021-01-07 21:30
Dupe of #96

**Closed by dessalines** 2021-01-07 21:30 UTC
