### ISSUE TITLE
Make it easier to browse communities on other instances.

### ISSUE THREAD

**Issue by kevincox** [LemmyNet/lemmy-ui#1397] opened 2023-06-19 19:45 UTC
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [ ] Is this a server side (not related to the UI) issue? Use the [Lemmy back end](https://github.com/LemmyNet/lemmy) repo.

### Is your proposal related to a problem?

Right now if you want to join a handful of communities on another instance it is quite tedious.

### Describe the solution you'd like.

It would be great to have an easy UI for listing and opening communities on another instance.

I'm thinking something like when looking at the page for a community there is a link to info about an instance including communities on that instance. Then you can just browse the list and open the links from the comfort of your instance's UI and subscribe with one click.

### Describe alternatives you've considered.

The best workflow I have found so far is:

1. Open the list of communities on the UI of the other instance.
2. For each interesting community
    a. Copy the ID such as `!nix@programming.dev`
    b. Search for the ID on your instances search page. (Note: Use "All" not "Communities" otherwise it won't be discovered)
    c. Follow the link in the result and open it.

### Additional context

- Trying to construct a URL directly such as `https://lemmy.ml/c/nix@programming.dev` won't work if your server doesn't yet know about that community.
- `/communities/listing_type/All/page/1` only shows known communities (obviously)
- The full `!nix@programming.dev` isn't shown for communities local to the instance (it just shows `!nix`). So you need to append the instance domain to it manually.

**Comment by Falmarri** [comment] 2023-06-20 20:53
Being able to list or search based on instance, rather than community name, is pretty important IMO. If for example I want to see what communities are on kbin, searching "kbin" doesn't actually return anything except for communities with "kbin" in their names, not the kbin instance itself

**Comment by SuperContraptionGuy** [comment] 2023-06-26 19:24
One major road block to viewing and joining a new community, especially a community older than your home instance when you are the first user to search for it, is that most of the posts, votes, and all of the comments are just completely un-federated. There is no sorting of posts according to the communities voting! There is no discussions! The value of the community is not evident. When we browse new communities, (from our own instance without opening a new logged out tab!) we need more context than has been fedderated up to that point. We need on-demand posts according to some search/feed, all their votes and most important, or all, comments.

**Comment by luthis1124** [comment] 2023-07-03 01:20
Just add a dropdown or list to select the community when you're looking at local communities in https://instance/communities?

It's easy enough to curl a list of communities from the other instance after you select it. 

This would be really great.

**Comment by jfryton** [comment] 2023-08-17 04:35
I like how Connect for Lemmy implements this. You can just click "View Instance" while viewing a community to access information about the instance and a list of communities there. It's easy to subscribe right from the list.

**Comment by dessalines** [comment] 2023-10-18 21:46
Dupe of #2951

**Closed by dessalines** 2023-10-18 21:46 UTC
Labels: enhancement, area: discovery

**Comment by kevincox** [comment] 2023-10-19 00:22
Presumably this was intended to reference https://github.com/LemmyNet/lemmy/issues/2951
