### ISSUE TITLE
Show context button does not work

### ISSUE THREAD

**Issue by gallrein** [LemmyNet/lemmy-ui#1999] opened 2023-07-28 18:31 UTC
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

When clicking the "Show context" button above a comment, the same comment is loaded instead of the parent comment.

Additionally, I noticed that parent comments are not shown anymore which was introduced earlier in c16488153f01fd355d36513396e30d817c7df4cb

This appears since the upgrade to 0.18.3 and is not present in 0.18.2

### Steps to Reproduce

1. Go to a comment that has a parent comment (e.g. [this one](https://lemmy.ml/comment/2074795))
2. Click "Show context"
3. Page refreshes but parent is not shown

### Technical Details

OS: macOS, Linux
Browser: Safari, Firefox

### Lemmy Instance Version

0.18.3

### Lemmy Instance URL

- https://lemmy.ml
- https://feddit.de

**Comment by Sh4d** [comment] 2023-07-28 21:00
Just a reproduction note that this seems to only happen on deeper nested comments. First level is fine.

Can look at https://lemmy.ca/comment/1689450 as an example.

**Comment by SomeoneStoleMyNickname** [comment] 2023-07-28 21:31
Here are two other examples: https://feddit.de/comment/1654364, https://feddit.de/comment/1654314.

It seems like show context now moves to another child node instead of moving up the comment tree to the next parent node.

**Comment by lionirdeadman** [comment] 2023-07-29 05:38
Seems like it would be related to https://github.com/LemmyNet/lemmy/issues/3767

**Comment by brihuang99** [comment] 2023-07-30 13:34
> Just a reproduction note that this seems to only happen on deeper nested comments. First level is fine.
> 
> Can look at https://lemmy.ca/comment/1689450 as an example.

I'm still getting this bug even on first level comments. Here's an [example](https://sopuli.xyz/comment/1622715)

**Comment by RocketDerp** [comment] 2023-07-31 20:50
Since 0.18.3 links to single comments seem mixed up, API returns the correct comment:  https://lemmy.ml/api/v3/comment?id=2119998  
`{"id":2119998,"creator_id":839930,"post_id":2613341,"content":"I'd say more like night terror if it's anything to do with Atlassian"`

lemmy-ui  shows the wrong comment: https://lemmy.ml/comment/2119998

**Comment by poVoq** [comment] 2023-08-02 13:09
This seems to be the same issue that is making the "more replies" button fail ever since 0.18.3

**Comment by RocketDerp** [comment] 2023-08-02 13:49
The example I posted  https://lemmy.ml/comment/2119998 has changed behavior, now it shows 3 comments instead of the single incorrect comment. I don't know if lemmy.ml has installed new code ot did a SQL fix.... or if some background process altered the datta.

**Comment by jakariyab** [comment] 2023-08-02 20:08
To add, 1 or 2 level nested "more replies" don't seem to work either. It'll just return the same reply again and again or keep loading for infinite amount of time.

**Comment by Mutant** [comment] 2023-08-03 04:03
This is affecting more than just "Show context". In some cases the 'Link' icons next to the comment will take you to the wrong comment (I've seen it for top-level comments at least).

It seems highly likely that the underlying cause is https://github.com/LemmyNet/lemmy/issues/3767 - the API call now returns comments in a different (wrong?) order. The UI seems to be taking the first comment in the list, but that is often the wrong one.

**Comment by Mutant** [comment] 2023-08-03 22:35
OK, so it seems like the problem is almost certainly caused by https://github.com/LemmyNet/lemmy/pull/3717, which disabled sorting of comments by parent path if the post_id was not supplied. So if the UI does not supply the post_id, it will get the list of comments back in an essentially random order. The UI either needs to supply the post_id, or the BE change needs to be rolled back to give the UI time to adapt to the change (I don't think it's only the official UI that is hit by what is effectively an undocumented change in API behaviour).

**Comment by dessalines** [comment] 2023-08-04 18:43
The UIs unfortunately cannot know the post ID beforehand, for routes like `/comment/id` . I've just opened a PR to fix the ordering issue.

**Comment by dessalines** [comment] 2023-08-04 20:33
I'll close this issue since it all seemed to be related to the mis-ordering of the comments from the back-end, and will be fixed by that PR. Sry again for this yall.

**Closed by dessalines** 2023-08-04 20:33 UTC
Labels: bug
