### ISSUE TITLE
In preview mode, when making a post, clicking on buttons in the WYSIWYG menu creates unnexpected/unpredictable responses.

### ISSUE THREAD

**Issue by K4LCIFER** [LemmyNet/lemmy-ui#2356] opened 2024-02-05 01:56 UTC
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

If you enter preview mode and click on any buttons in the WYSIWYG editor, it will put markdown formatting in essentially unpredictable places in the text.

### Steps to Reproduce

1. Create/edit a post
2. Write some text
3. Enter preview mode
4. Click buttons in the WYSIWYG menu, and observe that the markdown formatting syntax is placed in weird places.

### Technical Details

OS: Arch Linux, Kernel v6.7.3-arch1-1, KDE Plasma v5.27.10
Browser: Firefox v122.0

### Lemmy Instance Version

0.18.5

### Lemmy Instance URL

sh.itjust.works

**Comment by K4LCIFER** [comment] 2024-02-05 01:57
Potentially related: https://github.com/LemmyNet/lemmy-ui/issues/2355

**Comment by glibg10b** [comment] 2024-02-12 13:11
> it will put markdown formatting in essentially unpredictable places in the text.

The formatting markdown is placed based on whatever was selected before you switched to preview mode. I agree with #2355 - the WYSIWYG buttons should not be visible.

I think this issue should be considered a duplicate of that issue.

**Closed** 2024-02-16 22:57 UTC
Labels: bug
