### ISSUE TITLE
Make Lemmy instance logo clickable 

### ISSUE THREAD

**Issue by trashhalo** [LemmyNet/lemmy-ui#1292] opened 2023-06-14 23:34 UTC
### Is your proposal related to a problem?

I'd expect to click that to get back to the home screen but it is not clickable. 

### Describe the solution you'd like.

![Screenshot_20230614-193127](https://github.com/LemmyNet/lemmy-ui/assets/177491/4164a686-7a3f-49ef-8f2d-2329dbef30b6)

I touch that I go home to the page I get to by going to / on the instance. 

### Describe alternatives you've considered.

A home button somewhere else

**Comment by trashhalo** [comment] 2023-06-14 23:43
Oh weird it is clickable but sometimes it doesn't do anything when you click it. Whatever bad state I was in I got out now it works.

**Comment by ayan4m1** [comment] 2023-06-15 13:16
Can you close this issue? I can't reproduce using lemmy-ui from latest `main` branch. It could be something related to customizations your instance made.

**Comment by trashhalo** [comment] 2023-06-18 21:54
@ayan4m1

I managed to reproduce it. It happens if you go to create a post and you change your mind. Logo is not clickable to leave. 

https://photos.app.goo.gl/ZPZy8iE9u9hmZiHA6

**Comment by alectrocute** [comment] 2023-06-22 23:15
Resolved in 0.18.

**Closed by alectrocute** 2023-06-22 23:15 UTC
Labels: enhancement
