### ISSUE TITLE
404 on comment link

### ISSUE THREAD

**Issue by Tealk** [LemmyNet/lemmy-ui#807] opened 2022-09-28 13:41 UTC
### Issue Summary

Calling a comment is not possible, only 404 is displayed.
![image](https://user-images.githubusercontent.com/12276250/192792722-738b12dc-03d3-4081-ae62-27bf4ec96753.png)
![image](https://user-images.githubusercontent.com/12276250/192792837-f2389e3b-644f-47c2-99a1-d084da30397a.png)

### Steps to Reproduce

1. Open a post
2. click on show context, the fediverse icon

### Technical details

lemmy: 0.16.7
lemmyui: 0.16.7

```
Websocket closed. [client.js:2:936775](https://lemmy.rollenspiel.monster/static/js/client.js)
Retrying websocket connection... [client.js:2:936704](https://lemmy.rollenspiel.monster/static/js/client.js)
httpbase: https://lemmy.rollenspiel.monster/ [client.js:2:932776](https://lemmy.rollenspiel.monster/static/js/client.js)
wsUri: wss://lemmy.rollenspiel.monster/api/v3/ws [client.js:2:932805](https://lemmy.rollenspiel.monster/static/js/client.js)
isHttps: true [client.js:2:932831](https://lemmy.rollenspiel.monster/static/js/client.js)
isLoggedIn = true [client.js:2:1725863](https://lemmy.rollenspiel.monster/static/js/client.js)
Object { op: "UserJoin", data: {…} }
[client.js:2:183628](https://lemmy.rollenspiel.monster/static/js/client.js)
Fetching inbox unreads... [client.js:2:1738727](https://lemmy.rollenspiel.monster/static/js/client.js)
Object { op: "GetUnreadCount", data: {…} }
[client.js:2:183628](https://lemmy.rollenspiel.monster/static/js/client.js)
Fetching reports... [client.js:2:1738825](https://lemmy.rollenspiel.monster/static/js/client.js)
Object { op: "GetReportCount", data: {…} }
[client.js:2:183628](https://lemmy.rollenspiel.monster/static/js/client.js)
Fetching applications... [client.js:2:1738986](https://lemmy.rollenspiel.monster/static/js/client.js)
Object { op: "GetUnreadRegistrationApplicationCount", data: {…} }
[client.js:2:183628](https://lemmy.rollenspiel.monster/static/js/client.js)
The Notification permission may only be requested from inside a short running user-generated event handler. [831](https://lemmy.rollenspiel.monster/comment/831)
Connected to wss://lemmy.rollenspiel.monster/api/v3/ws [client.js:2:936618](https://lemmy.rollenspiel.monster/static/js/client.js)
Object { op: "UserJoin", data: {…} }
[client.js:2:1736860](https://lemmy.rollenspiel.monster/static/js/client.js)
Object { op: "GetUnreadRegistrationApplicationCount", data: {…} }
[client.js:2:1736860](https://lemmy.rollenspiel.monster/static/js/client.js)
Object { op: "GetReportCount", data: {…} }
[client.js:2:1736860](https://lemmy.rollenspiel.monster/static/js/client.js)
Object { op: "GetUnreadCount", data: {…} }
```

**Comment by dessalines** [comment] 2022-09-28 14:24
Dupe of #746

**Closed by dessalines** 2022-09-28 14:24 UTC
Labels: bug
