### ISSUE TITLE
Modlog Invalid time value

### ISSUE THREAD

**Issue by Tealk** [LemmyNet/lemmy-ui#1909] opened 2023-07-10 21:48 UTC
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

When I call modlog I get the message "Invalid time value".

### Steps to Reproduce

1. open Modlog

### Technical Details

docker-compose logs -f lemmy-ui

```
lemmy-ui_1  | RangeError: Invalid time value
lemmy-ui_1  |     at formatDistanceStrict (/app/node_modules/date-fns/formatDistanceStrict/index.js:113:11)
lemmy-ui_1  |     at u (/app/dist/js/server.js:2:98987)
lemmy-ui_1  |     at mi (/app/dist/js/server.js:2:969245)
lemmy-ui_1  |     at /app/dist/js/server.js:2:982146
lemmy-ui_1  |     at Array.map (<anonymous>)
lemmy-ui_1  |     at n.get (/app/dist/js/server.js:2:981790)
lemmy-ui_1  |     at a.renderModlogTable (/app/dist/js/server.js:2:977188)
lemmy-ui_1  |     at a.render (/app/dist/js/server.js:2:976592)
lemmy-ui_1  |     at renderVNodeToString (/app/node_modules/inferno-server/dist/index.cjs.js:193:35)
lemmy-ui_1  |     at renderVNodeToString (/app/node_modules/inferno-server/dist/index.cjs.js:280:27)
```

### Lemmy Instance Version

UI: 0.18.2-rc.2 BE: 0.18.1

### Lemmy Instance URL

https://lemmy.rollenspiel.monster/

**Comment by Eskuero** [comment] 2023-07-11 11:11
Related to this:
https://github.com/LemmyNet/lemmy-ui/issues/1899

**Comment by lionirdeadman** [comment] 2023-07-18 02:29
Closing as duplicate of https://github.com/LemmyNet/lemmy-ui/issues/1899

**Closed by lionirdeadman** 2023-07-18 02:29 UTC
Labels: bug
