### ISSUE TITLE
modlog page results in server error / no longer loads

### ISSUE THREAD

**Issue by slash-zero** [LemmyNet/lemmy-ui#1905] opened 2023-07-10 14:24 UTC
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

Current Behavior:

The modlog is no longer loading.  Instead the loading icon remains and the page never populates.  Reloading /modlog results in a server error. 

Note: this does not appear to be related to 0.18.2-rc.1 specifically, but instead related to banned users and their ban duration. Please see the comments below on the DB query which can resolve this. 

<img width="862" alt="image" src="https://github.com/LemmyNet/lemmy-ui/assets/5788688/4a30f0c1-705a-4b5b-9599-f3963fac8633">

Attempting to refresh the modlog page results in a "blank" `Server Error` page. 

### Steps to Reproduce

1. Start up the docker containers
2. Log in (if needed,) and try to access the modlog

### Technical Details

Mac OS, Safari Browser.

### Lemmy Instance Version

Any

**Comment by bootyberry** [comment] 2023-07-10 14:47
see #1899 
You'll have to run a query to fix the modlog after the invalid days federated out

**Comment by slash-zero** [comment] 2023-07-10 14:56
Note: as pointed out by @bootyberry, this query fixes the issue.

```
UPDATE mod_ban SET expires = NULL WHERE expires > now() + INTERVAL '10 years';
```

**Comment by geneccx** [comment] 2023-07-10 16:31
This is unrelated to 0.18.2 and the issue exists in previous versions as well, though yes a hotfix would be good.

**Comment by slash-zero** [comment] 2023-07-10 16:59
> This is unrelated to 0.18.2 and the issue exists in previous versions as well, though yes a hotfix would be good.

Updated the issue to reflect that.

**Comment by gregpxc** [comment] 2023-07-10 21:34
> Note: as pointed out by @bootyberry, this query fixes the issue.
> 
> ```
> UPDATE mod_ban SET expires = NULL WHERE expires > now() + INTERVAL '10 years';
> ```
> 
> I can confirm this query **_does_** fix the modlog page after upgrading to 0.18.2-rc.1.
> 
> In my opinion, this query should be included in the next lemmy release or hot fix so that folks who run their own instances don't have to manually do it.

No doubt a dumb question but I installed my Lemmy instance using Ansible and running commands with psql doesn't seem to be working nor does there seem to be a postgres user - how do I go about running this query?

**Comment by slash-zero** [comment] 2023-07-10 21:41
> how do I go about running this query?

I believe all ansible is doing is generating then docker containers. You would still connect to the db via the docker command. 

Your DB user should be in the lemmy.hjson config file and you can pass that user to the docker command then run the query from PSQL.

**Comment by gregpxc** [comment] 2023-07-10 21:51
> > how do I go about running this query?
> 
> I believe all ansible is doing is generating the docker containers. You would still connect to the db via the docker command.
> 
> Your DB user should be in the lemmy.hjson config file and you can pass that user to the docker command then run the query from PSQL.

Got it, pretty new to all this so I ran:
`docker ps`
Found the one with image "postgres:15-alpine" and copied the container ID
Then ran:
`sudo docker exec -it <container_name_or_id> psql -U lemmy`

That got me into the psql cli so I could run the query:
`UPDATE mod_ban SET expires = NULL WHERE expires > now() + INTERVAL '10 years';`

No doubt there's a one-liner for some of this but hopefully this is helpful for other noobs like me!

**Comment by jmreeder** [comment] 2023-07-16 21:43
gregpxc -- As a newbie admin myself I REALLY appreciate the instructions.  Let me be able to execute the command.

Unfortunately -- at least for me -- it did not fix this problem.  I still get the spinning circle with modlog not loading and a "server error" message if I refresh.  

Honestly though -- I don't think modlog has ever worked on my server, even before the upgrade to 0.18.2 .

Thanks,
Michael

**Comment by lionirdeadman** [comment] 2023-07-18 02:29
Closing as duplicate of https://github.com/LemmyNet/lemmy-ui/issues/1899

**Closed by lionirdeadman** 2023-07-18 02:29 UTC
Labels: bug
