### ISSUE TITLE
Timestamp tool-tip on edited posts shows original post date/time

### ISSUE THREAD

**Issue by Tmpod** [LemmyNet/lemmy-ui#437] opened 2021-10-02 11:32 UTC
### Issue Summary

The timestamp tool-tip on edits shows the published date/time instead of edited date/time.

### Steps to Reproduce

1. Make a post
2. Wait a minute or so, then edit it.
3. Hover the mouse over the 

### Technical details
N/A

### Screenshots

![imagem](https://user-images.githubusercontent.com/35771816/135714181-8146d3c7-a310-4f54-938d-7071180056e0.png)  
(in Portuguese; the tool-tip says `Thursday, 30th of September 2021 08:08`, while the text below the cursor says `seconds`)

**Comment by dessalines** [comment] 2021-10-03 15:29
Dupe of #438

**Closed by dessalines** 2021-10-03 15:29 UTC
Labels: bug
