### ISSUE TITLE
Show warning if "undetermined" language is not selected

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy-ui#941] opened 2023-02-20 15:10 UTC
There are reports from users complaining that they dont see any content after selecting languages. This problem usually happens because all content created before 0.17 and most content from other platforms doesnt have language tags, so its marked as "undetermined". So for the time being "undetermined" language should be selected under almost all circumstances. Otherwise there should be a warning shown.

For site and community languages there is a similar problem. If "undetermined" language is not allowed, users from many platforms such as Mastodon will not be able to participate at all. So a warning should be shown if it isnt selected.

**Comment by dessalines** [comment] 2023-02-20 23:55
Dupe of #930

**Closed by dessalines** 2023-02-20 23:55 UTC
Labels: enhancement
