### ISSUE TITLE
All comments expanded upon voting

### ISSUE THREAD

**Issue by tjkirch** [LemmyNet/lemmy-ui#1510] opened 2023-06-23 03:44 UTC
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

If I collapse some comments with their `-` button, then vote on another comment, all the collapsed comments are re-opened.  It's very hard to find my place again.

### Steps to Reproduce

1. Open a lemmy post.
2. Collapse some comments.
3. Vote on another comment.
4. See that all the comments you collapsed expand again.

### Technical Details

Windows 10, Firefox 114.0.1

### Lemmy Instance Version

0.18.0-rc.7

### Lemmy Instance URL

https://lemmy.ml/

**Comment by alectrocute** [comment] 2023-06-23 11:33
@dessalines @SleeplessOne1917 Pretty critical UX bug here.

**Comment by dessalines** [comment] 2023-06-23 11:57
This might have to be fixed in a later release. Don't worry, we're going to be a lot more frequent now that  `0.18.0` is coming out today.

**Comment by alectrocute** [comment] 2023-06-23 12:40
Should also note that comments re-expand upon any sort of voting, wether it's the main post, a comment, a comment reply, etc. I'm assuming this has to do with `editListImmutable`, or the way we're reassigning comments upon vote:

```ts
        s.commentsRes.data.comments = editComment(
          res.data.comment_view,
          s.commentsRes.data.comments
        );
```

**Comment by scme0** [comment] 2023-06-23 13:01
@alectrocute I've been poking around at this and I thought the same as you but when I tested an in-place update it still does it. In fact it seems to be more generally when `this.setState()` is called on the post.
I've tried things like:
```
this.setState({scrolled: true})
```
and it still makes all the comments get new props for some reason.

My knowledge of how inferno/react works at this point is pretty limited so I'm not sure how to solve the problem.

**Comment by SWW13** [comment] 2023-06-24 00:31
When interacting with a post on the feed (e.g. vote or save) all opened preview images are collapsed. This issue sounds like the same root cause, so reporting it here. (FE 0.18.0)

**Comment by SleeplessOne1917** [comment] 2023-06-24 00:35
I think this is due to some sort of unnecessary rerenders. The comment collapse state is stored in the CommentNode component, so if it gets destroyed and recreated, its collapse status will go back to the default state.

**Comment by scme0** [comment] 2023-06-24 02:47
I don't think the object is being destroyed and recreated. It is just that the `setState` call on the `Post` causes all `CommentNode`s to receive a call to the `componentWillReceiveProps` function which resets the state of each comment. We want this call to happen for the individual comment that is getting an up or down vote but I don't know why it's getting triggered for all comments.

**Closed** 2023-06-24 04:06 UTC
Labels: bug, critical
