### ISSUE TITLE
Enable rate limiting for creating communities

### ISSUE THREAD

**Issue by ManikandanUV** [LemmyNet/lemmy-ui#1851] opened 2023-07-07 15:00 UTC
### Requirements

- [X] This is a feature request and not a bug report. Otherwise, please create a new [bug report](https://github.com/LemmyNet/lemmy-ui/issues/new?assignees=&labels=bug%2Ctriage&projects=&template=BUG_REPORT.yml) instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this request (or a similar one) already exists.
- [X] It's a single feature. Please don't request multiple features in one issue.

### Describe the feature you'd like

Lots of bot accounts are creating communities in bulk. Setting up rate limiting would slow down the bulk creation of communities.

**Comment by lionirdeadman** [comment] 2023-07-21 05:21
Duplicate of https://github.com/LemmyNet/lemmy/issues/3452

**Closed** 2023-07-22 18:02 UTC
Labels: type: duplicate, enhancement
