### ISSUE TITLE
Don't show the "Next" button in the notifications list if there are no notifications on the next page

### ISSUE THREAD

**Issue by K4LCIFER** [LemmyNet/lemmy-ui#2648] opened 2024-08-02 01:37 UTC
### Requirements

- [X] This is a feature request and not a bug report. Otherwise, please create a new [bug report](https://github.com/LemmyNet/lemmy-ui/issues/new?assignees=&labels=bug%2Ctriage&projects=&template=BUG_REPORT.yml) instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this request (or a similar one) already exists.
- [X] It's a single feature. Please don't request multiple features in one issue.

### Describe the feature you'd like

Currently, the "Next" button is shown at the bottom of a page in the notification list even if there are no results on the next page. Clicking the button will show an empty page. I would suggest either not showing the "Next" button if there are no notifications or greying it out to show that it isn't applicable.

---

I wasn't sure if this was better reported as a bug or a feature. https://github.com/LemmyNet/lemmy-ui/issues/103 is related.

**Comment by dessalines** [comment] 2024-08-02 12:29
Dupe of #103 . We probably aren't going to add this as it'd require expensive count queries in the back end.

**Closed by dessalines** 2024-08-02 12:29 UTC
Labels: enhancement
