### ISSUE TITLE
If you delete the main community new users are still subscribed to it by default

### ISSUE THREAD

**Issue by NIXOYE** [LemmyNet/lemmy-ui#800] opened 2022-09-26 15:06 UTC
### Issue Summary

If you delete the main community new users are still subscribed to it by default. If they click that community which they are subscribed to it gives them an error stating the community doesn't exist. If you try and recreate the community with the same name it says community already exists. So its impossible to edit community 

there seems to be an open issue related here: https://github.com/LemmyNet/lemmy/pull/2450 
### Steps to Reproduce

delete the main community

**Comment by dessalines** [comment] 2022-09-26 15:15
Dupe of https://github.com/LemmyNet/lemmy/issues/2448

**Closed by dessalines** 2022-09-26 15:15 UTC
Labels: bug
