### ISSUE TITLE
search bar doesn't work on mobile 

### ISSUE THREAD

**Issue by PrincessMiki** [LemmyNet/lemmy-ui#931] opened 2023-02-12 09:31 UTC
Found a bug? Please fill out the sections below. 👍

For front end issues, use [lemmy-ui](https://github.com/LemmyNet/lemmy-ui)

If you have problems installing Lemmy, you should post in [!lemmy_support](https://lemmy.ml/c/lemmy_support).

### Issue Summary

Using firefox on redmi note 11, firefox.

Search button opens up the box but hitting the search option upon entering the details does nothing about 9/10 out of times.

### Steps to Reproduce

Type in search 

Press magnifying glass 

### Technical details

* Please post your log: `sudo docker-compose logs > lemmy_log.out`.
* What OS are you trying to install lemmy on? 
* Any browser console errors?

**Comment by dessalines** [comment] 2023-02-13 16:41
I can't verify this on firefox android. Hitting either enter or the search button does do the search. Could you provide more details?

**Comment by JackFromWisconsin** [comment] 2023-02-14 00:52
I can confirm I am also experiencing this same issue. I am using firefox on android 12. hitting the enter button or magnifying glass does not work. The box is also smaller than expected, instead of taking up the proper amount of horizontal space. I'll attack a couple of screenshots.

**Comment by JackFromWisconsin** [comment] 2023-02-14 00:55
![Screenshot_1](https://user-images.githubusercontent.com/118757222/218610112-7cbe81ac-91b7-4f70-945f-39be9f940da0.png)
![Screenshot_2](https://user-images.githubusercontent.com/118757222/218610120-fe2af4f6-f568-409e-98c6-97fcdef787aa.png)

sorry not a video but hitting enter or the magnificent glass does nothing.

**Comment by PrincessMiki** [comment] 2023-02-14 05:47
It's possible that the magnifying hit box shrunk and is too small to be clickable on some devices

**Comment by PrincessMiki** [comment] 2023-02-14 05:48
It's possible that the magnifying hit box shrunk and is too small to be clickable on some devices

I zoomed in all the way and the magnifying glass still is unclickable

**Comment by dessalines** [comment] 2023-02-18 00:20
Duplicate of #921

**Closed by dessalines** 2023-02-18 00:20 UTC
Labels: bug
