### ISSUE TITLE
Posting a comment without the language specified stuck at infinite loading

### ISSUE THREAD

**Issue by afeedhshaji** [LemmyNet/lemmy-ui#1880] opened 2023-07-08 14:48 UTC
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

When trying to post a comment in a different language, the button UI is stuck at loading. Refer the image below:

![lemmy_comment_bug](https://github.com/LemmyNet/lemmy-ui/assets/39899544/c34e3512-8746-4840-80b8-32699b4c83c9)

The API gave a 400 response with "language not allowed" error but the UI shows no indication of any errors and is stuck at loading. It would be great if we can stop the loading and show an error banner indicating the error reason. 

### Steps to Reproduce

1. Go to a post in Lemmy
2. Comment in a language other than English without picking the "Select Language" option

### Technical Details

OS: Linux
Browser: Firefox 114.0.1 (64-bit)
Device: Laptop

### Lemmy Instance Version

0.18.1

### Lemmy Instance URL

https://lemmy.world/

**Comment by Silver-Golden** [comment] 2023-07-12 13:41
From my own instance (0.18.1) trying to post a comment to lemmy.world I get this error in logs:

Language set to undefined

```
Jul 12 13:27:07 main-server lemmy_server[1960179]: 2023-07-12T13:27:07.908955Z  WARN Error encountered while processing the incoming HTTP request: lemmy_server::root_span_builder: language_not_allowed: language_not_allowed
Jul 12 13:27:07 main-server lemmy_server[1960179]:    0: lemmy_api_crud::comment::create::perform
Jul 12 13:27:07 main-server lemmy_server[1960179]:            with self=CreateComment { content: "Thats fantastic!\n\nWhat size are the stickers?  \nI find that most are too big for my liking", post_id: PostId(3982), parent_id: None, language_id: Some(LanguageId(37)), form_id: Some("markdown-form-upyJ6ky9gb2HPjq9q0>
Jul 12 13:27:07 main-server lemmy_server[1960179]:              at crates/api_crud/src/comment/create.rs:42
Jul 12 13:27:07 main-server lemmy_server[1960179]:    1: lemmy_server::root_span_builder::HTTP request
Jul 12 13:27:07 main-server lemmy_server[1960179]:            with http.method=POST http.scheme="https" http.host=lemmy.brendan.ie http.target=/api/v3/comment otel.kind="server" request_id=2d7f688f-02fd-42e8-9ddd-aeb64d7992e3 http.status_code=400 otel.status_code="OK"
Jul 12 13:27:07 main-server lemmy_server[1960179]:              at src/root_span_builder.rs:16
Jul 12 13:27:07 main-server lemmy_server[1960179]: LemmyError { message: Some("language_not_allowed"), inner: language_not_allowed, context: SpanTrace [{ target: "lemmy_api_crud::comment::create", name: "perform", fields: "\u{1b}[3mself\u{1b}[0m\u{1b}[2m=\u{1b}[0mCreateComment { content: \"Thats fantastic!\\n\\nWhat size are the stickers?  \\nI find that most are too big for my liking\", post_id: PostId(3982), parent_id: None, language_id: None, form_id: Some(\"
```
And with the language set to English, not sure why this is causing issues, maybe the enum of it changed?
```
`LemmyError { message: Some("language_not_allowed"), inner: language_not_allowed, context: SpanTrace [{ target: "lemmy_api_crud::comment::create", name: "perform", fields: "\u{1b}[3mself\u{1b}[0m\u{1b}[2m=\u{1b}[0mCreateComment { content: \"Thats fantastic!\\n\\nWhat size are the stickers?  \\nI find that most are too big for my liking\", post_id: PostId(3982), parent_id: None, language_id: Some(LanguageId(37)),
```

**Comment by lionirdeadman** [comment] 2023-07-18 20:51
Duplicate of https://github.com/LemmyNet/lemmy-ui/issues/1015

**Closed by lionirdeadman** 2023-07-18 20:51 UTC
Labels: bug, ux
