### ISSUE TITLE
User page fails to load when not logged in

### ISSUE THREAD

**Issue by dayinjing** [LemmyNet/lemmy-ui#507] opened 2021-11-23 19:04 UTC
### Issue Summary

When visiting a user when logged in for example nutomic's page you can see it going to ,

https://lemmy.ml/u/nutomic

You can query his user information in the api like,

```
curl https://lemmy.ml/api/v3/user?username=nutomic

```

When not logged in attempting to view the page will result in a `504 Gateway Time-out`

### Steps to Reproduce

1. Open up a private browser window
2. Make sure you are not logged into lemmy in the private browser window
3. go to https://lemmy.ml/u/nutomic 
4. See `504 Gateway Time-out` , and cry a little on the inside.

### Technical details

N/A

**Comment by dessalines** [comment] 2021-11-23 19:31
Dupe of #496

**Closed by dessalines** 2021-11-23 19:32 UTC
Labels: bug
