### ISSUE TITLE
[bug] issues seeing older posts in "active" and "hot" sorts

### ISSUE THREAD

**Issue by JackFromWisconsin** [LemmyNet/lemmy-ui#1844] opened 2023-07-07 06:03 UTC
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

When on "hot" or "active" sorts, it wi not display posts older than 5-10 days (differs based on community). When moving to any other sort, the older posts show up. 

### Steps to Reproduce

1. Select hot or active sort
2. Scroll down and/or go to next page(s)
3. Notice absolute lack of older posts
4.

### Technical Details

I'm on Firefox mobile, android 11.

### Lemmy Instance Version

UI v0.18.1-rc11 and BE v0.18.1-rc10

### Lemmy Instance URL

https://midwest.social

**Comment by stark1tty** [comment] 2023-07-07 12:30
This includes pinned posts.

**Comment by lionirdeadman** [comment] 2023-07-21 04:50
This is a duplicate of https://github.com/LemmyNet/lemmy/issues/3428 which was fixed (should be in next release) - closing.

**Closed by lionirdeadman** 2023-07-21 04:50 UTC
Labels: bug
