### ISSUE TITLE
Option to filter community list by instance

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy-ui#309] opened 2021-06-19 01:35 UTC
Look at this, you have to scroll more than a full page to find the first community which is not from lemmy.ml. Maybe we should even hide remote communities by default? Especially users who are not logged in probably care most about local content.

https://lemmy.161.social/communities

**Comment by dessalines** [comment] 2021-06-24 19:10
Good point... I should add a `Local / All` switch, and let it use your default local / all / subscribed settings ( which defaults to local for non-logged-in users. )

**Comment by dessalines** [comment] 2021-07-17 15:37
Dupe of #190

**Closed by dessalines** 2021-07-17 15:37 UTC
Labels: enhancement
