### ISSUE TITLE
In the main feed, if I have an image post expanded and upvote it, it will collapse. 

### ISSUE THREAD

**Issue by JediMaster25** [LemmyNet/lemmy-ui#1602] opened 2023-06-25 22:52 UTC
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Steps to Reproduce

1. Expand image post.
2. Vote.
3. It collapses.

### Lemmy Instance Version

0.18

### Lemmy Instance URL

https://lemmy.ml/

**Comment by tomjasinski** [comment] 2023-06-26 21:06
Was added 4 days ago #1484

**Comment by SleeplessOne1917** [comment] 2023-06-26 21:12
Closing: Duplicate of #1484

**Closed by SleeplessOne1917** 2023-06-26 21:12 UTC
Labels: bug, critical
