### ISSUE TITLE
Modlog doesn't load/500 error

### ISSUE THREAD

**Issue by cid214** [LemmyNet/lemmy-ui#2054] opened 2023-08-11 02:55 UTC
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

![logmod-500](https://github.com/LemmyNet/lemmy-ui/assets/83316375/fdba7acb-0e5e-45ae-aa34-4e3bfdbb58e0)

Started at some point prior to the UTC timestamps in the logs and was mentioned in the Matrix chat, and I could confirm I was seeing the same issue on my instance and went through the logs for the lemmy-ui container and captured that trace and 500 from nginx once it fails.

It's consistently replicable (at least, right now).

Am not completely sure this is strictly a front-end error, but the only logging details I've got are from the lemmy-ui container, so filing here since I have nothing showing any backend interaction.

### Steps to Reproduce

1. Go to /modlog
2. Hit refresh if you get an endless spinner to trigger the 500.

### Technical Details

Firefox, Win 11.

### Lemmy Instance Version

0.18.4

### Lemmy Instance URL

https://lemmy.uncomfortable.business

**Comment by BrooklynMan** [comment] 2023-08-11 02:58
confirmed. can’t load modlogs on lemmy.ml, lemmy.world, lemmy.ee, or beehaw.org

**Comment by lionirdeadman** [comment] 2023-08-11 03:18
I really hate that this bug not only exists but has existed for so long...

Duplicate of https://github.com/LemmyNet/lemmy-ui/issues/1899

**Closed by lionirdeadman** 2023-08-11 03:18 UTC
Labels: bug
