### ISSUE TITLE
Have an option to make points invisible

### ISSUE THREAD

**Issue by StaticallyTypedRice** [LemmyNet/lemmy-ui#122] opened 2021-01-09 03:00 UTC
@dessalines said that he would like to make Lemmy less addictive to mitigate the harm that social media can do, and I think one way of doing that is to not show the points on posts and comments. It's known that they can trigger brain responses that reinforce usage of of a social media platform. They can also mould users to conform to the "hive mind" instead of forming their own opinions. I've definitely experienced both effects, I'm sure many people here have too, either with Lemmy or other social media.

We could implement this as a setting per user or per instance, or both.

**Comment by dessalines** [comment] 2021-02-02 17:28
We need to add a back end setting for this.

**Comment by dessalines** [comment] 2021-04-09 16:34
Dupe of #241

**Closed by dessalines** 2021-04-09 16:34 UTC
Labels: enhancement
