### ISSUE TITLE
browsing to lemmy.example.com/c/mycommunity fails to show all /c/mycommunity content of the entire federated network

### ISSUE THREAD

**Issue by shodanx2** [LemmyNet/lemmy-ui#1674] opened 2023-06-28 18:13 UTC
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

If you go to lemmy.example.com/c/mycommunity and lemmy.another.com/c/mycommunity

You will notice that the content is not the same in both places, even if they are part of the same federation.

This is because under the current setup lemmy.example.com/c/mycommunity    filters to show only lemmy.example.com local content by default

A user has to take supplemental action to see posts from the rest of the federation, which is to say, most users most of the time will never see /c/mycommunity from outside their profile hosting instance.

This has severe consequences for federation of content it means that.

All users of /c/mycommunity will converge to the same single instance, there is no room for second place here. 

Not only all /c/mycommunity users will converge to thebigone.com/c/mycommunity, they will move their account there. 

This in turn will incide users to create communities on the same thebigone.com instance.

The effect is a constant push for centralization of /c/mycommunity to a single, biggest /c/mycommunity and then a push for centralization of all the biggest communities to move to the biggest instance. 

This breaking the reason for federation to exist.

lemmy.example.com/c/mycommunity most show all content from all federated instances, by default. 

It must not depend on users to create subscription to each existing /c/mycommunity to each existing instance either. 

Some people have proposed "use  https://lemmy.example.com/c/mycommunity@lemmy.another.com instead"

This is not a useful solution, users will not visit 700 permutation of this URL format for each existing federated instance. 

https://lemmy.example.com/c/mycommunity  must show all /c/mycommunity on all federated instances

Failure to do so is a lemmy destroying bug

### Steps to Reproduce

1. Go to /c/mycommunity in two instance
2.o bserve the content does not match
3.
4.

### Technical Details

This problem applies to all operating system, all web browser

NOTE : to developers, if this bug was introduced on purpose for ideological or political reasons, then please state so and close this bug thank you

### Lemmy Instance Version

0.18

### Lemmy Instance URL

https://thebiginstance.lemmy.ml/c/thebigcommunity

**Comment by sunaurus** [comment] 2023-06-28 18:29
Hi 👋 

1. This is not a bug
2. This is not for "ideological or political reasons"
3. /c/community@instanceA is a different community at /c/community@instanceB

Maybe it's helpful to think about it like this: when you send an e-mail to bob@google.com, you don't expect it to also reach bob@facebook.com - these are two entirely different e-mails. In the exact same way as the domain is part of an e-mail address, the instance name is also part of a community name.

Maybe discussion will be interesting to you: https://github.com/LemmyNet/lemmy-ui/issues/1113

**Comment by shodanx2** [comment] 2023-06-28 18:53
Lemmy is not email

If I post to 
https://lemmy.obscurethreeusersinstance.com/c/mycommunity

then people visiting https://lemmy.theirinstance.com/c/mycommunity  will not see my post

Are you expecting users of /c/mycommunity   to visit

https://lemmy.theirinstance.com/c/mycommunity
https://lemmy.theirinstance.com/c/mycommunity@lemmy.another.com
https://lemmy.theirinstance.com/c/mycommunity@lemmy.obscurethreeusersinstance.com
https://lemmy.theirinstance.com/c/mycommunity@lemmy.example.com
https://lemmy.theirinstance.com/c/mycommunity@thebiginstance.lemmy.ml

I have also read #1113 this does solve the issue.

Imagine what that would look like

https://lemmy.theirinstance.com/c/mycommunity@lemmy.example.com,lemmy.another.com,lemmy.obscurethreeusersinstance.com,
lemmy.example.com,thebiginstance.lemmy.ml


Do you believe more than 95% would create such an URL, containing 700 instances and that they would do this for every existing community ?

No, like multireddit on reddit, this is a compromise feature no one but the most hardcore users would use, and it would have no impact on the site as a whole.

It would not prevent the push for moving everything to lemmy.thebiginstance.com/c/thebigcommunity  , the current system is decentralized in name only, the entire system still rotates on its center of mass

**Comment by shodanx2** [comment] 2023-06-28 19:20
The multireddit idea is a dead end compromise to ensure decentralization of communities does not happen

To illustrate why the multireddit idea will substitute what I am suggesting here, here is what a very incomplete "multireddit" like URL for /c/mycommunity might look like

This list, is very old, probably does not even contain half the currently existing instances.

This list would need to be updated on an hourly basis.

This list would be subject to tampering.

This list probably does not fit in an url searchbar.



[https://lemmy.myinstance.com/c/mycommunity@](https://lemmy.theirinstance.com/c/mycommunity@lemmy.example.com,lemmy.another.com,lemmy.obscurethreeusersinstance.com)lemmy.world,lemmy.ml,feddit.de,sh.itjust.works,lemmy.one,lemmynsfw.com,lemmy.ca,lemmy.fmhy.ml,lemm.ee,lemmy.blahaj.zone,lemmy.dbzer0.com,lemmygrad.ml,programming.dev,sopuli.xyz,discuss.tchncs.de,lemmy.sdf.org,vlemmy.net,aussie.zone,feddit.uk,startrek.website,dormi.zone,feddit.it,infosec.pub,pawb.social,feddit.nl,lemmy.burger.rodeo,burggit.moe,slrpnk.net,feddit.dk,lemmy.nz,mander.xyz,feddit.cl,reddthat.com,lemmy.zip,latte.isnot.coffee,szmer.info,dataterm.digital,exploding-heads.com,pathofexile-discuss.com,monyet.cc,iusearchlinux.fyi,yiffit.net,sub.wetshaving.social,geddit.social,lemmyrs.org,monero.town,partizle.com,mtgzone.com,toast.ooo,lemmy.studio,lemmy.click,lemmy.film,lemmy.radio,fanaticus.social,rammy.site,lemmy.villa-straylight.social,lemmy.whynotdrs.org,ttrpg.network,lemmy.antemeridiem.xyz,r-sauna.fi,lemmy.cafe,ash1-lem-i1-u4829.vm.elestio.app,discuss.online,thegarden.land,lemmy.spacestation14.com,bookwormstory.social,lemmy.eus,forum.basedcount.com,possumpat.io,lemmy.wtf,thelemmy.club,lemmy.perthchat.org,compuverse.uk,preserve.games,lemmy.tf,dmv.social,lemmy.eco.br,social.fossware.space,lemmy.podycust.co.uk,diggit.xyz,feddit.ch,picify.podycust.co.uk,feddit.nu,bolha.social,lemmy.ko4abp.com,lib.lgbt,lemmy.kya.moe,terefere.eu,lemmyfly.org,sffa.community,lemmy.picote.ch,feddit.ro,apollo.town,tucson.social,aiparadise.moe,seemel.ink,eslemmy.es,poptalk.scrubbles.tech,lemmy.justin.rs,booty.world,lemmy.srv.eco,group.lt,lemdit.com,news.cosocial.ca,wirebase.org,crystals.rest,suppo.fi,lemmy.blugatch.tube,baomi.tv,links.dartboard.social,lemmy.ptznetwork.org,notdigg.com,cubing.social,fadoverso.pt,dubvee.org,digipres.cafe,fig.systems,lemmyunchained.net,lemmy.easfrq.live,lemmy.bulwarkob.com,links.rebel.ar,lemmy.juggler.jp,lm.bittervets.org,yall.theatl.social,lemmy.suchmeme.nl,derpzilla.net,lemmy.nexus,lemmy.onlylans.io,lm.korako.me,lemmy.rollenspiel.monster,wayfarershaven.eu,outpost.zeuslink.net,lemmy.graz.social,bbs.darkwitch.net,lemmy.4d2.org,baraza.africa,lemmy.loomy.li,centennialstate.social,weiner.zone,bbs.9tail.net,voxpop.social,lemmy.funami.tech,skein.city,quex.cc,dot.surf,lemmy.today,lemmy.reckless.dev,feddit.pontual.social,federated.community,mindshare.space,lemmy.cock.social,lemmy.pro,frig.social,lemmy.kemomimi.fans,mylem.my,goddess.name,tagpro.lol,lemmy.jamesj999.co.uk,prime8s.xyz,oceanbreeze.earth,lemmy.roombob.cat,eviltoast.org,sub.rdls.dev,feddit.jp,keeb.lol,lemmy.stuart.fun,lemmy.darmstadt.social,lemmy.einval.net,lemmy.themainframe.org,lm.madiator.cloud,posta.no,wizanons.dev,databend.run,tabletop.place,lemmy.wiuf.net,lemmy.dormedas.com,lemmy.jpiolho.com,linkopath.com,coeus.sbs,lemmy.avata.social,whiskers.bim.boats,lemmy.media,lemmy.g97.top,darmok.xyz,keylog.zip,lemmy.iys.io,lem.monster,normalcity.life,lolimbeer.com,bulletintree.com,lemmy.tebro.fi,no.lastname.nz,sowhois.gay,lemmy.starlightkel.xyz,lemmy.ninja,lemmywinks.com,lemmy.vanoverloop.xyz,foros.fediverso.gal,lemmy.coeus.icu,lemmy.place,lemmy.wizjenkins.com,social.dn42.us,l.roofo.cc,voltage.vn,lemmy.piperservers.net,feddit.nz,feditown.com,lemmy.pathoris.de,lemmy.run,lemmy.krobier.com,lm.put.tf,livy.one,moot.place,lemmy.my.id,lemmy.loungerat.io,feddi.no,social.doudp.com,lemmy.alexland.ca,shork.online,lemmyfi.com,laguna.chat,lemmy.marud.fr,communick.news,narod.city,links.hackliberty.org,lemmy.rat.academy,lemmy.jigoku.us.to,lemmy.linuxuserspace.show,orava.dev,forum.liberatedsystems.co.uk,sha1.nl,tslemmy.duckdns.org,moto.teamswollen.org,dgngrnder.com,lemmy.minji.xyz,social.sour.is,lemmy.burningboard.net,nlemmy.nl,lemmy.bunbi.net,fenbushi.site,lef.li,lm.inu.is,iboughtthisdomainbecauseithoughtitscheap.uk,lemmy.ppl.town,1337lemmy.com,lsmu.schmurian.xyz,stanx.page,melly.0x-ia.moe,lemmy.mildgrim.com,lemmy.elmusfire.xyz,wallstreets.bet,lem.lyk.pw,lemmy.jtmn.dev,lemmy.nilskrau.de,lemmy.zroot.org,philly.page,s.jape.work,lemmy.pipipopo.pl,lm.qtt.no,lemmy.eic.lu,dendarii.alaeron.com,civilloquy.com,parapheum.com,lemmy.sbs,federated.ninja,lemmy.scam-mail.me,lemmy.cablepick.net,lemmy.gtfo.social,ripo.st,lemmy.xoynq.com,lemmy.norbz.org,lemmy.snoot.tube,lemmy.skillissue.dk,lemmy.jamestrey.com,insane.dev,lemmy.nrd.li,lemmy.intai.tech,thechurchofmemes.com,lemmy.plasmatrap.com,lemmy.1204.org,lemmy.remotelab.uk,invariant-marxism.red,red.cyberhase.de,lemmy.scottlabs.io,lemmy.gamingnight.uy,www.jrz.city,lemmy.nerdcore.social,bluuit.org,lemmy.funkyfish.cool,lemmy.trippy.pizza,techy.news,lemmy.fromshado.ws,lemmy.comfysnug.space,zemmy.cc,lululemmy.com,lemmy.timdn.com,lemmy.sascamooch.com,labdegato.com,lemmy.quad442.com,lemmy.nerdcruft.net,proit.org,lemmonade.marbledfennec.net,lemmy.lukeog.com,lemmy.tillicumnet.com,anarch.is,clatter.eu,lemmy.staphup.nl,lemmy.direktoratet.se,fedibb.ml,kek.henlo.fi,nrsk.no,lemmy.emopolarbear.com,caint.org,social.hamington.net,lemmy.glasgow.social,lemmy.mlsn.fr,lm.halfassmart.net,lemmy.calvss.com,bigfoot.ninja,lemmy.pipe01.net,lemmy.jmtr.org,fedit.io,links.lowsec.club,lemmy.pussthecat.org,lemmy.link,lemmy.notdead.net,hakbox.social,lemmy.arclight.pro,mobilemmohub.com,hammerdown.0fucks.nl,chat.maiion.com,lm.melonbread.dev,lemmy.astheriver.art,lemmy.havocperil.uk,lemmy.douwes.co.uk,lem.serkozh.me,le.fduck.net,lemmy.simpl.website,lemmy.mazurka.xyz,lemmy.lpcha.im,lemmy.isamp.com,lemmy.shwizard.chat,lemmy.nerdcave.us,feddit.fun,hqueue.dev,lemmony.click,lucitt.social,feddit.win,lemmy.beru.co,lm.gsk.moe,animoe.xyz,lemmy.temporus.me,lemmy.thanatos.at,lemmy.philipcristiano.com,lemmy.l00p.org,lemmy.vrchat-dev.tech,endofti.me,werm.social,lemmy.fbxl.net,hoodlem.me,fanexus.com,lemmy.morrisherd.com,r.rosettast0ned.com,lemmy.mbl.social,cnvrs.net,lemmy.dominikoso.me,local106.com,lemthony.com,lemmy.dupper.net,le.mnau.xyz,lemmy.wraithsquadrongaming.com,lemmy.weiser.social,spgrn.com,zerobytes.monster,c.calciumlabs.com,lemmy.tancomps.net,demmy.co.uk,lemmy.doomeer.com,lemmy.steken.xyz,lemmy.fwgx.uk,014450.xyz,lemmy.pub,lemmy.fauxreigner.net,lemmy.fribyte.no,lemmy.weckhorst.no,lemmy.songsforno.one,lemmy.chiisana.net,nunu.dev,lemmy.dyslexicjedi.com,lemmy.deadca.de,lemmy2.addictmud.org,lemmywinks.xyz,lemmy.thepixelproject.com,lemmy.pcft.eu,social.poisson.me,lemmy.stellarvortex.com,lemmy.mywire.xyz,greg.city,lemmy.calebmharper.com,lemmy.gregw.us,lemmy.nope.ly,lemmus.org,lemmy.amyjnobody.com,mesita.link,localghost.org,acqrs.co.uk,lemmy.x3i.tech,lemmy.kagura.eu,lemmit.xyz,lemmit.online,lm.rdbt.no,lemmy.meli.dev,algebro.xyz,lemmy.timwaterhouse.com,lemmy.kiberness.xyz,toons.zone,orzen.games,lemmy.webgirand.eu,lemmy.moonling.nl,lemmyonline.com,lemmyland.com,tortoisewrath.com,mlem.a-smol-cat.fr,lemmy.comm.social,jamie.moe,lemmy.fakecake.org,snkkis.me,lm.byteme.social,lemmy.gross.hosting,lemmy.tarsis.org,lemmy.javant.xyz,feddit.strike23.de,solstice.etbr.top,0v0.social,lemmy.self-hosted.site,mcr.town,lemmy.srv0.lol,popplesburger.hilciferous.nl,lemmy.lif.ovh,lemmy.recursed.net,lemmy.kghorvath.com,lemmy.devils.house,versalife.duckdns.org,upvote.au,social.cyb3r.dog,lemmy.0x3d.uk,rustyshackleford.cfd,lemmy.dustybeer.com,lemmy.onitato.com,lemmy.skl.works,lemmy.selfip.org,endlesstalk.org,lmy.drundo.com.au,lemmy.eatsleepcode.ca,lemmings.online,thegarden-u4873.vm.elestio.app,jemmy.jeena.net,sedd.it,lemmy.6px.eu,lm.williampuckering.com,lemmy.pe1uca.dev,lemmy.cornspace.space,occult.social,kleptonix.com,negativenull.com,lemmy.dnet.social,drachennetz.com,lemmy.littlejth.com,moose.best,digitalgoblin.uk,lemmy.the-goblin.net,lemmy.pryst.de,re.tei.li,links.decafbad.com,lemmy.hamrick.xyz,netmonkey.tech,lemmy.sh,lemmy.kizaing.ca,lemmy.sumuun.net,lemmy.monster,lemmy.timon.sh,thaumatur.ge,xrs.cx,community.nicfab.it,lemmy.escapebigtech.info,lemmyverse.org,lemmy.thesmokinglounge.club,lemmy.stark-enterprise.net,shitposting.monster,kale.social,lemmy.schmeisserweb.at,leby.dev,lemmy.munsell.io,lemmy.mlaga97.space,lemmy.pastwind.top,mylemmy.win,lemmy.management,lemmy.proxmox-lab.com,lemmy.livesound.world,lemmy.leafylibrary.uk,lemmy.schlunker.com,lemmy.nopro.be,lemmy.haigner.me,l.biendeo.com,lemmy.sebbem.se,lemmy.austinwadeheller.com,lemmy.graphics,lemmy.helvetet.eu,lemmy.beckmeyer.us,leddit.minnal.icu,radiation.party,lemmy.seifert.id,fjdk.uk,lemmy.fail,lemmy.tr00st.co.uk,lemmy.jacaranda.club,lemmy.website,lemmy.xce.pt,hc.frorayz.tech,lemmy.vinodjam.com,jalim.xyz,xffxe4.lol,granitestate.social,nc.gnzl.cl,lemmy.zell-mbc.com,lemmy.uhhoh.com,lemmy.jasonsanta.xyz,social.ggbox.fr,l.bxy.sh,ascy.mooo.com,leaf.dance,lemmy.lucaslower.com,lemmy.fdvrs.xyz,l.jugregator.org,lemmy.cloudhub.social,omg.qa,areality.social,lemmy.gareth.computer,matts.digital,lemmy.commodore.social,forkk.me,lemmy.chromozone.dev,community.adiquaints.moe,discuss.dizl.de,lemmy.pit.ninja,bubblesthebunny.com,lemmy.clueware.org,lemmy.mb-server.com,feedly.j-cloud.uk,lemmy.socdojo.com,lemmy.serverfail.party,libreauto.app,actuallyruben.nl,typemi.me,lemmy.helios42.de,lmmy.tvdl.dev,rabbitea.rs,lemmy.k6qw.com,lemmy.borlax.com,psychedelia.ink,lemmy.stormlight.space,lemmy.dudeami.win,social.vmdk.ca,lemmy.benrasich.com,lemmy.pineapplemachine.com,www.korzekwa.io,lemmy.gjz010.com,biglemmowski.win,lem.cochrun.xyz,lemmy.austinite.online,abstract-scones.crabdance.com,lem.southcape.social,lem.simple-gear.com,meganice.online,lemmy.bringdaruck.us,lemmypets.xyz,lemmy.fediverse.jp,reddrefuge.com,lem.elbullazul.com,femboys.bar,lemmerz.org,lemmydeals.com,lemmybedan.com,lemmy.fyi,lemmy.davidfreina.at,distress.digital,lemmy.cook.gg,lemmy.koski.co,lemmy.dcrich.net,selfhosted.forum,lemmy.mixdown.ca,lemmy.wxbu.de,lemmy.dekay.se,links.wageoffsite.com,lemmy.jpaulus.io,links.roobre.es,notlemmy.notawebsite.fr,hive.atlanten.se,lemitar.meta1203.com,thediscussion.site,lemmy.amxl.com,syrma.cc,lemmy.virtim.dev,l.twos.dev,lemmy.s9m.xyz,lemmy.sysctl.io,lemmy.vepta.org,lemmy.bradis.me,eventfrontier.com,lemmy.jlh.name,l.nulltext.org,lemmy.dork.lol,pwzle.com,linkage.ds8.zone,lemmy.aucubin.de,lemmy.w9r.de,lemmy.belclayfer.net,lemmy.zone,lemmy.nauk.io,silicon-dragon.com,lemmy.loutsenhizer.com,lemmy.vyizis.tech,lemmy.lylapol.com,shinobu.cloud,tezzo.f0rk.pl,lemmy.game-files.net,link.fossdle.org,gonelemmy.xyz,wilbo.tech,l.plabs.social,beer.andma.la,lemmy.demonoftheday.eu,lemmy.pwzle.com,lemmy.zelinsky.dev,lemmy.mira.pm,heckoverflow.net,lme.smn.sh,culture0.cc,lemmy.anonion.social,lemmy.saik0.com,lemmy.thias.xyz,lemmy.elest.io,whata.clusterfsck.com,aulem.org,l.vidja.social,lmmy.net,lemmy.thetaits.net,wumbo.buzz,lemmy.uncomfortable.business,snuv.win,lemmy.keychat.org,lemmy.best,lemmy-u3.vm.elestio.app,hyperfair.link,lemmy.aguiarvieira.pt,lemmy.itermori.de,lemmy.pierre-couy.fr,cigar.cx,lemmy.help,lemmy.grygon.com,lemmy.tanktrace.de,lm.electrospek.com,lemmy.matthe815.dev,lemmy.bloodmoon-network.de,lm.paradisus.day,fed.rosssi.co.uk,lemmy.atheos.org,thesidewalkends.io,androiddev.network,lemmy-ujt-u4842.vm.elestio.app,leddit.social,lm.kalinowski.dev,lemmy.johnpanos.com,lemmy.kitsuna.net,thesimplecorner.org,lemmy.knocknet.net,lemmy.davidbuckley.ca,lemmy.coupou.fr,lemmy.syrasu.com,lemmy.umainfo.live,lemmy.rimkus.it,lem.free.as,discuss.ntfy.sh,lemmy.pec0ra.ch,lemmy.foxden.party,lemmy.sprawl.club,lemmy.iswhereits.at,butts.international,lmmy.io,lemmy.schuerz.at,pasta.faith,rational-racoon.de,lemmy.obrell.se,lemmy.gmprojects.pro,lemmy.ubergeek77.chat,lemmy.helheim.net,lemmit-u4849.vm.elestio.app,sambaspy.com,theotter.social,lemmy.sweevo.net,lemmy.ch3n2k.com,lemmy.secnd.me,ani.social,stammtisch.hallertau.social,discuss.jacen.moe,lemmy.korgen.xyz,donky.social,retarded.dev,lostcheese.com,lemmy.maples.dev,lemmy.2kd.de,neodrain.net,lemmy.beebl.es,lemmy.frozeninferno.xyz,support-futbol-u4947.vm.elestio.app,support.futbol,social.nerdhouse.io,lemmy.cnschn.com,lm.runnerd.net,lemmy.friheter.com,lemmy.hosted.frl,drak.gg,lm.suitwaffle.com,cavy.rocks,lemmy.smoothbrain.org,lemmy.scav1.com,lemmy.perigrine.ca,lemmy.mrm.one,lemmy.belegost.net,lemmy.andiru.de,iceorchid.net,einweckglas.com,lemmy.edgarchirivella.com,lemmy.karaolidis.com,lemmy.brief.guru,lm.curlefry.net,lemmy.nikore.net,lemmy.telaax.com,lemmy.sedimentarymountains.com,lemmy.azamserver.com,lemmy.mooo.com,l.1in1.net,lemmy.unfiltered.social,lemmy.modshiftx.com,lemmy.theonecurly.page,lemmy.mutation.observer,lemmy.sietch.online,lemmy.meridiangrp.co.uk,feddit.tech,lemmy.mambastretch.com,lemmy.fedihub.social,feddit.pl,lemmy.l0nax.org,lemmy.freewilltiger.page,lemmy.techstache.com,lemmy.qpixel.pw,lemmy.pen15.club,lemmy.safe-internet.org,lemmy.tario.org,lemmy.mats.ooo,lemnt.telaax.com,glasstower.nl,p9.wtf,lemmy.tobyvin.dev,lemmy.soontm.de,lemmy.appeine.com,lemmy.ghostplanet.org,lemmy.hpost.no,lemmy.lettucegarden.net,drlemmy.net,badblocks.rocks,scif6.nsalanparty.com,notlemmy.site,lemmy.cultimean.group,lemmy.fucs.io,lemmy.batlord.org,lemmy.croc.pw,fedi.shadowtoot.world,lemmy.deev.io,lmmy.ylwsgn.cc,lemmy.mayes.io,skwerl.dev,le-me.xyz,lemmy.mxh.nu,lemmy.pxm.nl,nwdr.club,discuss.as200950.com,lemmy.whalesinspace.de,lemmy.vskr.net,lemmy.shattervideoisland.com,opendmz.social,lemmy.corrigan.xyz,lemmy.nathaneaston.com,lemmy.productionservers.net,lemmy.r6e.dev,0xdd.org.ru,lemmy.root6.de,lemmy.dlgreen.com,lemmy.fun,lemmy.freddeliv.me,lemmy.therhys.co.uk,thepride.hexodine.com,talka.live,lemmy.m1k.cloud,social.fr4me.io,lemmy.fredhs.net,lemmy.rhymelikedi.me,feddit.at,purrito.kamartaj.xyz,bethe.kingofdog.de,lemmy.kodeklang.social,dsilo061298.ddns.net,nonewfriends.club,soccer.forum,lemmy.wyattsmith.org,liminal.southfox.me,lemmy.brad.ee,lemmy.mypinghertz.com,lemmy.gsp8181.co.uk,surlesworld.com,lemmyis.fun,lm.sethp.cc,lemmy.datatekniker.dev,lemmy.arun.cloud,lemmy.barnacles.one,lemmy.macaddict89.me,lemmy.holmosapien.com,feddit.site,mayheminc.win,lem.zevs.me,lemmy.toot.pt,lemmy.finance,lemmy.halfbro.xyz,rlyeh.cc,lemmy.services.coupou.fr,ue.reddiverse.umbraluvine.xyz,mh.znark.us,gertie.uk,lemmy.naga.sh,lemmy.mpcjanssen.nl,lemmy.neeley.cloud,overctrl.dbzer0.com,lemmy.sarcasticdeveloper.com,l.mathers.fr,lemmy.rubenernst.dev,lemmy.dogboy.xyz,lemmy.jasondove.me,lemmy.eldarerathis.com,lemmy.enchanted.social,sublight.one,botnet.club,lemmy.meissners.me,lemmy.albertoluna.es,lemmy.zkr.io,readit.space,lemmy.ravc.tech,lemmy.scurry.io,anime-pub.moe,lemmy.buller.cc,lmy.dotcomitsa.website,lemmy.namwen.me,lemmy.funkylab.xyz,lemmygrid.com,mlemmy.de,lemmy.flugratte.dev,feddit.eu,pootusmaximus.xyz,lemmy.fap.ie,lemmy.hellwhore.com,lemmy.austinvaness.com

**Comment by shodanx2** [comment] 2023-06-28 19:26
So, ok I will give you a compromise

How about 

http://lemmy.myinstance/a/mycommunity

You can keep the club house at http://lemmy.myinstance/c/mycommunity

but http://lemmy.myinstance/a/mycommunity  , that's an automatic agglomeration of all federated instance's /c/mycommunity

I would instead have put the clubhouse on /l/ and /c/ for the actual federated content but accident of history, most people will use /a/.

Then we can move on to the real topic of user-led moderation. Rather than the current approach of choking the community first and moderation second.

**Comment by 0xAnansi** [comment] 2023-06-28 21:22
What happens when someone decide to use a community in some federated server that is free to create or empty to spam content that has nothing to do with the name of the community?

If I create a disposable instance that I federate, create a lot of communities based on a dictionary, and fill them all with some commercial link, porn or even illegal content, that would propagate to all servers using this kind of feature or am I understanding incorrectly? What if I spin up hundreds of such instances?

That would also most likely make every instance owner legally liable for distributing/storing illegal material in most countries in the world.

**Comment by shodanx2** [comment] 2023-06-28 21:55
> spam content that has nothing to do with the name of the community

Early downvotes, content will be deprioritized and rejected by user's content sorting algorithms

> fill them all with some commercial link, porn or even illegal content

same as spam


> That would also most likely make every instance owner legally liable

No, protected by section 230 and equivalents 


Again, strangling the community to make moderation easier  is back-assward design

You start with all the content and then user-led moderation tool gets refined to empower users to navigate the swamp.

If you drain swamp, you create an ecological disaster and no further effort will un-extinct the flora and fauna that's been extinguished

**Comment by SleeplessOne1917** [comment] 2023-06-30 15:13
Closing issue because OP fundamentally does not understand how federation works, and the suggestion is an antifeature.

**Closed by SleeplessOne1917** 2023-06-30 15:13 UTC
Labels: bug

**Comment by shodanx2** [comment] 2023-06-30 21:22
Decentralization is not an anti-feature, except for mods and owners of course, who are disempowered by decentralization

To me the obvious problem cause by bug #1674 can be illustrated by this exchange

https://old.reddit.com/r/Piracy/comments/14exyff/a_message_from_lemmy_to_uspez/joxgsed/

Users, when told to migrate from /r/piracy to /c/piracy, ask /c/piracy but on which server ?

![image](https://github.com/LemmyNet/lemmy-ui/assets/10621885/32eb62bf-c7b6-454d-a72b-93c9991da7ca)


Lemmy is young, it's not too late to fix this decentralization destroying behaviour. 

But every day that this is not fixed, users continue to think that 

But now, the few users who didn't realize that lemmy under this configuration, is just recreating reddit with extra steps

They all will  go to "lemmy.dbzer0.com/c/piracy"

Because that's where everyone else will go. 

And if you go and post elsewhere, because decentralization is broken, nobody will see your posts and comment. 

Instead of there being a /c/piracy community on lemmy, there is now just one centralized piracy community on lemmy.dbzer0.com/c/piracy

There is only a centralized community and centralized communities will inevitably and obviously be leveraged against itself by its moderators and instance owner when the lootbag gets big enough.

And I should specify for the pedants I'm using /c/piracy as an example here. This will happen with every community.

Nobody is going to go to 700 instance URLs in sequence to see /c/piracy on all instances.  Any post outside of thebigcommunity and thebiginstance, will not be seen, it's pointless to post elsewhere.
