### ISSUE TITLE
Images in new image posts are removed if the text box is selected then deslected (0.19.4)

### ISSUE THREAD

**Issue by Demigodrick** [LemmyNet/lemmy-ui#2522] opened 2024-06-09 15:01 UTC
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

When creating a new image post, then adding some text into the text box, the uploaded image will then vanish when the user deselects the text box, so the user will need to upload the image again.

As far as I can tell, this is purely a UI issue, the image appears to have uploaded correctly, it's just removed from the new post.

### Steps to Reproduce

1. Create new post & use the upload button
2. Click into the text box
3. Click out of the text box
4. Image vanishes

### Technical Details

Lemmy 0.19.4

### Lemmy Instance Version

0.19.4

### Lemmy Instance URL

Lemmy.zip

**Comment by SleeplessOne1917** [comment] 2024-06-12 16:05
I was able to reproduce this on lemmy.ml but not locally. So far it's confirmed to occur on lemmy.ml and lemmy.zip. Is anyone else viewing this issue encountering the bug on any other instances running 0.19.4? I'm wondering if it has something to do with configuration instead of the source code.

**Comment by Demigodrick** [comment] 2024-06-12 16:14
@sunaurus does this occur on lemm.ee? 


I could be wrong, but I suspect its linked to #2523 given its similar behavior, which does occur on lemm.ee.

**Comment by SleeplessOne1917** [comment] 2024-06-12 17:23
I tested this again locally, only this time I checked out the 0.19.4 tag. I encountered the bug then.

Since this bug no longer appears in the main branch, I am closing this issue.

**Closed by SleeplessOne1917** 2024-06-12 17:23 UTC
Labels: bug
