### ISSUE TITLE
Certain collections of remote communities will always report "Subscribe Pending" despite waiting days for the request

### ISSUE THREAD

**Issue by SineSwiper** [LemmyNet/lemmy-ui#1869] opened 2023-07-07 23:41 UTC
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

While subscribing to various communities, I've been noticing certain clusters of remote communities are always stuck on "Subscribe Pending".  For example, I have a large batch of communities from both sh.itjust.works and kbin.social that won't subscribe from my account on lemmy.dbzer0.com.

### Steps to Reproduce

1. Hit Subscribe
2. Wait
3. Don't get subscribed.  Ever.

### Technical Details

Firefox on Windows

### Lemmy Instance Version

UI: 0.18.1-rc.11 BE: 0.18.1-rc.10

### Lemmy Instance URL

https://lemmy.dbzer0.com/c/Games@sh.itjust.works

**Comment by lionirdeadman** [comment] 2023-07-21 05:36
Duplicate of https://github.com/LemmyNet/lemmy-ui/issues/1315

Note that subscriptions are not retried automatically so you may want to do so manually.

**Closed by lionirdeadman** 2023-07-21 05:36 UTC
Labels: bug, type: duplicate
