### ISSUE TITLE
Toggle to always open external link in a new tab 

### ISSUE THREAD

**Issue by DMTryptamines** [LemmyNet/lemmy-ui#634] opened 2022-04-25 14:04 UTC
I always end up leaving lemmy and losing my tabs because by default clicking an external link opens it in the same tab you're currently using. When I'm done reading articles I usually just close them right away which also closes my lemmy tab! Then I have to reopen the site and find the post again so I can comment or upvote. This would be a mega pain if I didn't just leave myself logged in on the browser. 

What I am proposing is a toggle in your personal settings (or instance config maybe?) that changes the default behaviour to always opening a new tab when clicking an external link. A step further maybe this could also do the same when clicking a post, user or community in lemmy.

Not a high urgency feature request for sure but I do think enabling customization of user workflow would go a long way in user satisfaction and making the transition easier.

**Comment by dessalines** [comment] 2022-04-25 20:55
Any reason why you can't use middle-click / right click-open in new tab?

We will never have auto-open-in-new-tab on by default, because it breaks accessibility, and because that behavior is unpredictable for most sites. 

If you'd like to submit a PR for adding this setting, I wouldn't be opposed to it.

**Comment by DMTryptamines** [comment] 2022-04-25 21:24
I'm just hearing about middle click from you and that works pretty well actually, neato :) I usually right click or hold ctrl and click which accomplishes the same but they are both 2 actions as opposed to one but your middle click suggestion actually solves that. 

As said it's pretty low priority so I'm all good parking it for now, I use this setting on Reddit so I always fumble the transition and makes the experience a little annoying.

**Comment by Nutomic** [comment] 2023-06-13 20:58
Duplicate of #282.

**Closed by Nutomic** 2023-06-13 20:58 UTC
Labels: enhancement
