### ISSUE TITLE
More descriptive message instead of "No posts" in communities with posts

### ISSUE THREAD

**Issue by Kojoley** [LemmyNet/lemmy-ui#2536] opened 2024-06-13 21:38 UTC
### Requirements

- [X] This is a feature request and not a bug report. Otherwise, please create a new [bug report](https://github.com/LemmyNet/lemmy-ui/issues/new?assignees=&labels=bug%2Ctriage&projects=&template=BUG_REPORT.yml) instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this request (or a similar one) already exists.
- [X] It's a single feature. Please don't request multiple features in one issue.

### Describe the feature you'd like

Currently when posts are filtered out completely "No posts" is displayed, it is confusing (see https://github.com/LemmyNet/lemmy-ui/issues/1860). When there are any posts in the community it should say something like "No posts are shown to you (check your settings)" and when there are really "No posts" it could say "No one posted anything here yet" instead.

Preferably, in place of "(check your settings)" it would list possible filters that could've resulted in "No posts" (like "you've opted-out of nsfw content; you've restricted languages shown to you; you don't see posts from blocked by you users; the instance this community is hosted on is in your block list;").

**Comment by dessalines** [comment] 2024-07-21 13:36
Dupe of #1860

**Closed by dessalines** 2024-07-21 13:36 UTC
Labels: enhancement
