### ISSUE TITLE
Default image for new communities

### ISSUE THREAD

**Issue by Seb3thehacker** [LemmyNet/lemmy-ui#526] opened 2021-12-15 04:19 UTC
When creating new communities there is no image by default. It would be nice to have an image be set automatically, maybe it could be a random color with the first letter of the new sublemmy in the center. This will make all sublemmys look much nicer and not be off-center on the site.

**Comment by dessalines** [comment] 2021-12-15 15:18
Dupe of #522

**Closed by dessalines** 2021-12-15 15:18 UTC
Labels: enhancement
