### ISSUE TITLE
Login broken in webkit - Impossible to login from Safari (macOS and iOS)

### ISSUE THREAD

**Issue by nicfab** [LemmyNet/lemmy-ui#676] opened 2022-05-31 05:00 UTC
It's impossible to login from Safari (macOS or iOS) my Lemmy instance (https://community.nicfab.it) even after the upgrade to 0.16.5 

```
remote: Enumerating objects: 4, done.
remote: Counting objects: 100% (4/4), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 4 (delta 1), reused 4 (delta 1), pack-reused 0
Unpacking objects: 100% (4/4), 423 bytes | 141.00 KiB/s, done.
From https://github.com/LemmyNet/lemmy-ansible
   f921a3d..a58766b  main       -> origin/main
 * [new tag]         0.16.5     -> 0.16.5
Updating f921a3d..a58766b
Fast-forward
```

Here is the image of the error from the console

![CleanShot 2022-05-31 at 06 58 44@2x](https://user-images.githubusercontent.com/24752671/171096065-225842f8-b422-4a64-a79b-5b1de3cb1c48.png)

You closed the issue [#669](https://github.com/LemmyNet/lemmy-ui/issues/669#issue-1251875852), but it remains, and it has not been solved (macOS 12.4 - M1).
Please, verify it.

**Comment by dessalines** [comment] 2022-05-31 12:09
Add this to your inventory/hosts line in lemmy ansible:

`lemmy_version=0.16.4 lemmy_ui_version=0.16.5`

Dupe of https://github.com/LemmyNet/lemmy-ui/issues/669

**Closed by dessalines** 2022-05-31 12:09 UTC
Labels: bug

**Comment by nicfab** [comment] 2022-05-31 12:14
> Add this to your inventory/hosts line in lemmy ansible:
> 
> `lemmy_version=0.16.4 lemmy_ui_version=0.16.5`
> 
> Dupe of #669

Thank you very much @dessalines 
Now it works. I will wait for the next upgrade.
