### ISSUE TITLE
websocket loop error reporting in Safari

### ISSUE THREAD

**Issue by medivh63** [LemmyNet/lemmy-ui#745] opened 2022-07-30 15:39 UTC
When I'm on chrome everything is fine, only in Safari it recurs 。How do I solve this problem, I don't see an example in the documentation

<img width="1377" alt="image" src="https://user-images.githubusercontent.com/30036788/181923682-11fe99be-6c48-4f3d-b0a8-7ce597cf5ea6.png">

**Comment by sam365724** [comment] 2022-09-10 12:42
I can confirm, that safari is broken on mac os.

```
Refused to connect to wss://domain.com/api/v3/ws because it does not appear in the connect-src directive of the Content Security Policy.
i — client.js:2:183632
```

https://stackoverflow.com/questions/68746912/safari-gives-error-refused-to-connect-to-because-it-does-not-appear-in-th

@dessalines Is there a quick fix for this? How can i change the CSP?

**Comment by sam365724** [comment] 2022-09-10 12:52
The problem is that the wsUriBase is wrong, it should be wss:// in the csp, but it's acually ws:// 

Where can i change that in the config?

**Comment by Nutomic** [comment] 2022-09-12 09:39
This problem should be fixed already in main branch, although we dont have any Apple devices to test with. [Here is the current CSP](https://github.com/LemmyNet/lemmy-ui/blob/main/src/server/index.tsx#L36).

If you run your own Lemmy instance, you could compile from source to get the fix. Basically checkout 0.16.6 tag, apply changes in the file I linked above, then `docker build` and deploy docker image on your server.

**Comment by sam365724** [comment] 2022-09-13 18:42
Could you push a new 0.16.7 rc version for this please? Then i can easily use the docker image.

**Comment by Nutomic** [comment] 2022-09-13 20:31
There is actually `dessalines/lemmy-ui:0.16.7-rc.2` already out, you can try that and see if it fixes the problem.

**Comment by dessalines** [comment] 2022-09-13 21:23
`0.16.7` is building now, should be done in 30 mins or so.

**Comment by sam365724** [comment] 2022-09-13 23:25
Confirmed that 0.16.7 works on Safari.

**Closed** 2022-09-14 10:52 UTC
Labels: question
