### ISSUE TITLE
[Bug]: leaving tab open to main feed in Firefox can cause high RAM/CPU usage

### ISSUE THREAD

**Issue by maxwood-forester** [LemmyNet/lemmy-ui#1385] opened 2023-06-19 04:08 UTC
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [ ] Is this a server side (not related to the UI) issue? Use the [Lemmy back end](https://github.com/LemmyNet/lemmy) repo.

### Summary

Sometimes, when leaving a tab open in Firefox with a Lemmy instance loaded at the main feed (equivalent to r/all), after several hours, very high RAM and CPU usage can result.

### Steps to Reproduce

1. leave a tab open to the main / combined feed in Firefox
2. wait several hours

### Technical Details

Behavior seen on Firefox 102.11 ESR and 114 on Debian and Mint flavors of Linux, respectively.

I will look at the console next time it happens.

### Version

0.17.4

**Comment by s3rvant** [comment] 2023-06-21 13:17
Confirmed however only took 3 minutes for the tab to crash:

Ubuntu 23.04
Firefox 114.0.1
i9-13900H
32gb RAM

Watched about:processes and observed 100% CPU entire duration and steady climb of RAM usage up until tab crashed. At that time RAM usage for the tab was at 16gb. Specifically tested on beehaw.org.

**Comment by Banzai51** [comment] 2023-06-21 13:32
Can confirm.
Windows 10
Firefox 114.0.1
CPU: 5800x3D
RAM: 64GB

Will slowly chew up RAM, notice it as I use Lemmy, especially forwarding/back on page, or changing my viewing from the defaults (subscribed-Hot) to something like Local - New.  If I close the Lemmy tab it goes away.

**Comment by ozoned** [comment] 2023-06-21 14:52
Also seeing this with Firefox 114.0.1 on Fedora 38.  I downgraded to 111.0.1-1.fc38 and it seemed like it was stopped, but it did slowly grow.  With 114.0.1 it definitely happens in minutes and halts my system due to swapping so much.

It's with the Isolated Web Container process of Firefox.  This does not happen with Chromium.  So I'm wondering if this is a bug in Firefox that is just exacerbated by Lemmy.

**Comment by happilyretirednobody** [comment] 2023-06-21 22:42
This may be fixed in the Firefox code already. I've been running a lemmy tab in Firefox Nightly (116.0a1) for a few hours now, and both the total memory & the Isolated Web Container memory seem to be stable.

**Comment by ozoned** [comment] 2023-06-22 00:37
I installed the beta version, 115.0b8, and it's fine.  I think this is a memory leak issue with the Isolated Web Container code in Firefox.

**Comment by s3rvant** [comment] 2023-06-22 01:10
Firefox version 114.0.2 is available now and after updating the issue is gone.

**Comment by Banzai51** [comment] 2023-06-22 10:56
The instance I'm on upgraded the UI to 0.18.0-rc.4, and I haven't seen the issue since. This morning I noticed Firefox was now 114.0.2 as well.

**Comment by ozoned** [comment] 2023-06-22 12:41
Just upgraded to 114.0.2 and issue is resolved here as well.  Seems like a memleak in Firefox that's been resolved quickly.

**Comment by alectrocute** [comment] 2023-06-23 02:11
Thanks for monitoring this one, everyone. Looks like we can close this out.

**Closed by alectrocute** 2023-06-23 02:11 UTC
Labels: bug
