### ISSUE TITLE
Clicking a link opens a new tab

### ISSUE THREAD

**Issue by k5jat** [LemmyNet/lemmy-ui#1242] opened 2023-06-13 20:42 UTC
### Is your proposal related to a problem?

Currently, when you click an external site on my lemmy, it will go directly to the new site and my site becomes a part of their history. For years, it's been my practice to open new tabs when clicking an external link from my websites. This is done with the hopes that once they are done with whatever they're doing on the external site, they continue their journey on my site.

### Describe the solution you'd like.

This can be solved by adding the **target=”_blank”** attribute to link code. 

Something like: `<a href="https://lemmy.website" target="_blank">Lemmy.Website</a>`

### Describe alternatives you've considered.

We could always ask the users to middle mouse-click, but that's not really practical.

**Comment by Nutomic** [comment] 2023-06-13 20:58
Duplicate of #634 and #282, use the search function.

**Closed by Nutomic** 2023-06-13 20:58 UTC
Labels: enhancement
