### ISSUE TITLE
Restore scroll state when navigating back to the previous page

### ISSUE THREAD

**Issue by rgb-one** [LemmyNet/lemmy-ui#149] opened 2021-01-29 01:24 UTC
For backend issues, use [lemmy-ui](https://github.com/LemmyNet/lemmy)

### Is your proposal related to a problem?

When navigating to previous pages, whether it be from page 2 to page 1 or from a specific post back to the page it is listed on, the scroll state of the page isn't preserved. What happens is, after you go back to the previous page, it starts back from the top; so you have to scroll back to where you were on the page.

### Describe the solution you'd like

The solution would be to keep the page at area it was last scrolled to when going back to that page from the last. As it works with server rendered pages. 

### Describe alternatives you've considered

 I can see that an Ajax request is sent to fetch the data when a page is visited. Probably some kind of caching or state management would help.

### Additional context

(Write your answer here.)

**Comment by Nutomic** [comment] 2021-01-29 13:34
This is a duplicate of #18.

**Closed by Nutomic** 2021-01-29 13:34 UTC
Labels: enhancement
