### ISSUE TITLE
Display Local/Global on Frontpage does not reflect user setting (but setting works)

### ISSUE THREAD

**Issue by molkemon** [LemmyNet/lemmy-ui#1150] opened 2023-06-10 13:29 UTC
Setting the default listing to global in User Settings works as intended, it now lists stuff from other instances. 

However, the local/global switch on the frontpage still is set to local. It's not a big issue but just adds to the instances confusion for new users... 

![image](https://github.com/LemmyNet/lemmy-ui/assets/1060874/64990a63-95dc-43d7-86e3-f22c4fc64e0c)

Also if the user setting is set to global, the communities list should also list other instances by default, but you still have to manually switch there.

**Comment by fheft** [comment] 2023-06-10 14:28
Duplicate of #1053

**Comment by jsit** [comment] 2023-06-23 21:46
This seems to work for me now on 0.18.0; I've selected "All" in my user settings, the home feed shows All, and the switcher menu at the top of the feed shows "All" is selected.

<img width="717" alt="Screenshot 2023-06-23 at 5 46 25 PM" src="https://github.com/LemmyNet/lemmy-ui/assets/643417/274d49ac-bcf2-41d2-a8ef-5cba6fcbf200">

@dessalines Can be closed?

**Comment by lionirdeadman** [comment] 2023-07-18 02:38
Closing as fixed :)

**Closed by lionirdeadman** 2023-07-18 02:38 UTC
Labels: bug
