### ISSUE TITLE
Make images on markdown appear where the cursor is

### ISSUE THREAD

**Issue by Porrumentzio** [LemmyNet/lemmy-ui#94] opened 2020-12-03 08:08 UTC
In version `0.8.9`, when writing posts on markdown format, using the _photo_ icon to upload an image does not upload it where the cursor is, or just on the selected characters, but on the bottom of the writing.
The uploaded image on markdown format should appear where the cursor is.

**Comment by dessalines** [comment] 2021-01-24 04:42
Dupe of another closed issue.

**Closed by dessalines** 2021-01-24 04:42 UTC
