### ISSUE TITLE
[Bug] :  No error management en 400 error when posting without language

### ISSUE THREAD

**Issue by 0xAnansi** [LemmyNet/lemmy-ui#1751] opened 2023-07-02 10:42 UTC
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

Linked to my other issue: https://github.com/LemmyNet/lemmy/issues/3451

When commenting on a thread that has no language set, if you don't explicitly set a language, the API returns a 400 error.

This error is not shown to the user, and the "comment" button shows as infinitely loading without any feedback.

### Steps to Reproduce

1. Create a post without selecting language
2. Comment on it without selecting language
3. Check console

`{"error":"language_not_allowed"}`

4. The post button infinitely spins

![image](https://github.com/LemmyNet/lemmy-ui/assets/72401951/5b79f1ad-9082-420b-83dc-8c835e169936)

### Technical Details

Server side error shows a 400 http status with body `{"error":"language_not_allowed"}` 

### Lemmy Instance Version

UI: 0.18.1-rc.7

### Lemmy Instance URL

https://jlai.lu

**Comment by lionirdeadman** [comment] 2023-07-18 20:50
Duplicate of https://github.com/LemmyNet/lemmy-ui/issues/1015

**Closed by lionirdeadman** 2023-07-18 20:50 UTC
Labels: bug, duplicate
