### ISSUE TITLE
Do not hide posts with same URL when viewing community feed

### ISSUE THREAD

**Issue by Die4Ever** [LemmyNet/lemmy-ui#2323] opened 2024-01-13 19:34 UTC
### Requirements

- [X] This is a feature request and not a bug report. Otherwise, please create a new [bug report](https://github.com/LemmyNet/lemmy-ui/issues/new?assignees=&labels=bug%2Ctriage&projects=&template=BUG_REPORT.yml) instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this request (or a similar one) already exists.
- [X] It's a single feature. Please don't request multiple features in one issue.

### Describe the feature you'd like

If 2 posts have the same URL link in the same community, I don't think they should be hidden. That feature is mostly for decluttering your main feed from crossposts. 

I just made a post that coincidentally had the same URL link as a much older post, and I was confused why it wasn't showing up on the community. Then I saw it got some upvotes and realized people were seeing it in the normal feed since the other post is much older my new post was hitting their feeds but the old post is long gone.

**Comment by Die4Ever** [comment] 2024-03-04 03:01
related to #2104

**Comment by Die4Ever** [comment] 2024-04-17 23:05
also the Subscribed feed should not be hiding crossposts

**Comment by dessalines** [comment] 2024-08-27 17:21
Dupe of #2104

**Closed by dessalines** 2024-08-27 17:21 UTC
Labels: enhancement
