### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'person_blocks')

### ISSUE THREAD

**Issue by kromonos** [LemmyNet/lemmy-ui#496] opened 2021-11-18 20:13 UTC
Lines like the following appear in the log files at irregular intervals:

```
lemmy-ui_1  | isHttps: false
lemmy-ui_1  | No JWT cookie found.
lemmy-ui_1  | http://0.0.0.0:1234
lemmy-ui_1  | TypeError: Cannot read properties of null (reading 'person_blocks')
lemmy-ui_1  |     at t.o.setPersonBlock (/app/dist/js/server.js:2:668206)
lemmy-ui_1  |     at new t (/app/dist/js/server.js:2:667864)
lemmy-ui_1  |     at renderVNodeToString (/app/node_modules/inferno-server/dist/index.cjs.js:170:28)
lemmy-ui_1  |     at renderVNodeToString (/app/node_modules/inferno-server/dist/index.cjs.js:221:20)
lemmy-ui_1  |     at renderVNodeToString (/app/node_modules/inferno-server/dist/index.cjs.js:221:20)
lemmy-ui_1  |     at renderVNodeToString (/app/node_modules/inferno-server/dist/index.cjs.js:303:35)
lemmy-ui_1  |     at renderVNodeToString (/app/node_modules/inferno-server/dist/index.cjs.js:307:39)
lemmy-ui_1  |     at renderVNodeToString (/app/node_modules/inferno-server/dist/index.cjs.js:221:20)
lemmy-ui_1  |     at renderVNodeToString (/app/node_modules/inferno-server/dist/index.cjs.js:337:37)
lemmy-ui_1  |     at renderVNodeToString (/app/node_modules/inferno-server/dist/index.cjs.js:221:20)
lemmy_1     | [2021-11-18T20:08:47Z INFO  lemmy_apub::http] Received shared inbox activity {"@context":"https://www.w3.org/ns/activitystreams","id":"https://mastodon.social/users/Eliane#delete","type":"Delete","actor":"https://mastodon.social/users/Eliane","to":["https://www.w3.org/ns/activitystreams#Public"],"object":"https://mastodon.social/users/Eliane","signature":{"type":"RsaSignature2017","creator":"https://mastodon.social/users/Eliane#main-key","created":"2021-11-18T20:08:01Z","signatureValue":"DXDkIdrQI18TcJYyZGgDvL6nbwPJlnwz5h9bz6mWzwl1vIm7vTiKb3PaB/u4VCEuPkXn0EYrZa+rXwCXQXgQhMTtL83PboaPNBjyMx46pEy5tzhjHenlO02ouzD39VfWAtXBA7/15rEqQz4rSN0x9UuYutlUkhQKfkvzq/QSzieywcSliiawm/LsAsPOJbFrUsVgwWvOIoB5ik6XqSh129ekzJldAAqpMhf+vLMqbyyGRBqTNX0GfdS/U/hDfIYZplNr/5lIt86n9dlbT15p3vGH+0L4Y7Lbde68Z6QjxqyMJbIAZmHXrwuV6L5kP69NdqPRwD2BoLi1LacisBYunQ=="}}
lemmy_1     | [2021-11-18T20:08:47Z INFO  lemmy_apub_lib::object_id] Fetching remote object https://mastodon.social/users/Eliane
lemmy_1     | [2021-11-18T20:08:48Z INFO  lemmy_apub::http] Verifying activity https://mastodon.social/users/Eliane#delete
lemmy_1     | [2021-11-18T20:08:48Z INFO  lemmy_apub::http] Receiving activity https://mastodon.social/users/Eliane#delete
```
I'm on Lemmy 0.14.1

**Comment by dessalines** [comment] 2021-11-18 21:14
Dupe of #491

**Closed by dessalines** 2021-11-18 21:15 UTC
Labels: bug
