### ISSUE TITLE
Dynamically importing date-fns locales other than en-US fail

### ISSUE THREAD

**Issue by mikeesto** [LemmyNet/lemmy-ui#1574] opened 2023-06-25 03:16 UTC
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

https://github.com/LemmyNet/lemmy-ui/blob/dd43827d6737e80fd01897eb665dff9df4b0b98f/src/shared/utils/app/setup-date-fns.ts#L10-L15

If a user's browser is set to prefer something other than en-US, for example en-GB, then this import fails with the following error:

<img width="1221" alt="Screen Shot 2023-06-25 at 1 14 25 pm" src="https://github.com/LemmyNet/lemmy-ui/assets/21051488/d1d6d516-5a89-4d49-85a9-2a93ec7a0f83">

### Steps to Reproduce

1. Use a browser that has a preferred locale to something other than en-US; or
2. Manually change `lang` to `en-GB` or another locale supported by date-fns

### Technical Details

Chrome, running lemmy locally

### Lemmy Instance Version

0.18

**Comment by alectrocute** [comment] 2023-06-27 15:37
@jsit @SleeplessOne1917 We should remove `date-fns` entirely, especially since the timezone support is totally borked.

**Comment by SleeplessOne1917** [comment] 2023-06-27 15:58
Should we go back to using Moment? Also, @alectrocute wasn't there an NPM library you shared in the dev matrix room that looked like a promising fix?

**Comment by alectrocute** [comment] 2023-06-27 15:59
Yeah, @SleeplessOne1917, the `date-fns-tz` project. We should probably go back to using moment.js and switch the libraries in the future in a separate branch where we can do thorough testing. 😌

**Comment by dessalines** [comment] 2023-06-29 11:51
Is this one still an issue? Or did the above PR fix it?

**Comment by alectrocute** [comment] 2023-06-29 12:35
Still an issue, a big one.

**Comment by sunaurus** [comment] 2023-06-29 12:55
@alectrocute how to reproduce? It's importing for me without issues now

**Comment by alectrocute** [comment] 2023-06-29 12:59
@sunaurus 

- Go to a production instance, eg. https://voyager.lemmy.ml.
- Change language in user settings. 
- Observe app break and error in console.

**Comment by sunaurus** [comment] 2023-06-29 13:08
Can't reproduce, are you sure you're not getting an older cached client.js?

**Comment by alectrocute** [comment] 2023-06-29 15:52
Resolved in `0.18.1-rc.4`.

**Closed by alectrocute** 2023-06-29 15:52 UTC
Labels: bug, critical
