### ISSUE TITLE
Create post pops "This instance is private." and then spinner spins forever

### ISSUE THREAD

**Issue by TurkeyMan** [LemmyNet/lemmy-ui#648] opened 2022-05-17 05:32 UTC
### Issue Summary

A summary of the bug.

Clicking "Create a post" in a new community in a brand new lemmy instance shows red pop-up message "This instance is private." in lower left and then shows a blue spinner thing which sits forever.
If I then press F5, the page refreshes to the create post page, and I can create a post.
Posting works; just using the "Create a post" button on the right doesn't work.

### Steps to Reproduce

- Installed a brand new lemmy instance
- Followed the prompts to configure the instance (choose 'private instance' in configuration)
- Create a community
- Enter that community
- Click "Create a post" on the right
- Note the red pop-up saying "This instance is private." and then the spinning blue thing that sits forever.

**Comment by dessalines** [comment] 2022-06-08 14:36
Sorry, just been swamped with other issues. Might be a while till I can get to this.

**Comment by sam365724** [comment] 2022-08-24 04:33
@dessalines See this duplicate with root cause found: #761

**Comment by dessalines** [comment] 2022-08-29 18:14
Dupe of #761

**Closed by dessalines** 2022-08-29 18:14 UTC
Labels: bug
