### ISSUE TITLE
Navigation does nothing when editing something

### ISSUE THREAD

**Issue by dullbananas** [LemmyNet/lemmy-ui#1175] opened 2023-06-11 15:23 UTC
### Issue Summary

Clicking things in the navigation bar does nothing when editing something

### Steps to Reproduce

1. Select "create post"
2. Type something
3. Select anything in the navigation bar
4. Nothing happens

### Technical details

Safari on iOS 16.5

UI: 0.17.4-rc.4

Console output:
```
e is not a function. (In 'e(t)', 'e' is "Are you sure you want to leave?")
forEach@[native code]
call@https://lemmy.ml/static/js/client.js:2:985780
C@https://lemmy.ml/static/js/client.js:2:990815
t@https://lemmy.ml/static/js/client.js:2:991117
G@https://lemmy.ml/static/js/client.js:2:995188
ae@https://lemmy.ml/static/js/client.js:2:286510
@https://lemmy.ml/static/js/client.js:2:286069
```

**Comment by fheft** [comment] 2023-06-11 20:33
Duplicate of #1139 

Let's hope it gets fixed soon…

**Comment by SleeplessOne1917** [comment] 2023-06-13 01:57
Closing because duplicate.

**Closed by SleeplessOne1917** 2023-06-13 01:57 UTC
Labels: bug
