### ISSUE TITLE
Use full width of the page: design request

### ISSUE THREAD

**Issue by jcklpe** [LemmyNet/lemmy-ui#801] opened 2022-09-27 01:26 UTC
Howdy. [I posted awhile back](https://github.com/LemmyNet/lemmy-ui/issues/550) about trying to get involved more with lemmy in an open source fashion. 

It's sometimes a little hard to know how to get involved in open source stuff with design but I have recently been working for my day job on an open source project as a designer so I have some ideas. 

I was thinking it might be helpful to make design recommendations in the form of github tickets. Really basically the same thing as a feature request but focused on aspects of design. 

Originally I was thinking about trying to get a full on design system defined for ya'll but I burnt myself out at my last job, and need some rest from that kind of work. I also don't know enough about rust to get the project set up on my local machine and directly make changes in CSS or refactor ya'll's styling directly myself and I think there probably needs to be more integration between design system and technical implementation work than I can really spare energy for. So maybe this will be helpful, maybe not. Consider this an experiment. 

Anyway here's my first recommendation: full width page

![image](https://user-images.githubusercontent.com/9451726/192407403-b81a3eed-0361-4ca2-8e1d-77dbc28a9047.png)

I understand that the the max-width main content pattern is built into the bootstrap framework that lemmy was built using but I would recommend going wider. 

For actual posts I would recommend still hugging the sides of the browser but to keep the width of text limited still so that you can follow [optimal line length requirements](https://baymard.com/blog/line-length-readability). 

![image](https://user-images.githubusercontent.com/9451726/192408543-17fe5ea8-7ba3-46b6-ae5f-60c558a85f88.png)

Hexbear already does the full width thing and I think it's a good idea to adopt it.

**Comment by Nutomic** [comment] 2022-09-27 09:19
Did you read the [development instructions](https://join-lemmy.org/docs/en/contributing/contributing.html)? Especially with Docker it should be relatively easy, and you can [ask on Matrix](https://matrix.to/#/#lemmydev:matrix.org) if anything is unclear.

About your proposed change, it might make sense to allow the side to be wider, but i think there should still be a maximum width for very big/wide screens.

**Comment by dessalines** [comment] 2022-09-27 16:46
Dupe of #799

**Closed by dessalines** 2022-09-27 16:46 UTC
Labels: enhancement
